### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Jhanvi12** [fhstp/k-AnonML#1]
Hi , **I am getting import error** . As written in requirement file  I have installed every package and have python 2. I have downloaded code and tried to run , but unable to .Pls help me to run the code sucessfully .

![image](https://user-images.githubusercontent.com/36741795/117582844-a417ea80-b121-11eb-8c5e-420f3ecb86d4.png)

**Comment by tobiasdam** [comment]
Hi!
As stated in the top-level [`README.md`](https://github.com/fhstp/k-AnonML/blob/main/README.md) our code uses python3 __not__ python2 and it is not possible to run the anonymisation modules directly.

> The `README.md` files inside the modules are left for reference to the original repository only

Please use `pip3` to install the requirements and run `python3 baseline_with_repetitions.py` to get usage instructions.
Aside from that I advise to use Linux or WSL, since the XGBoost version that we used cannot be installed on Windows with pip. Upgrading XGBoost might work, e.g. `pip3 install xgboost --upgrade`
